version: "3.7"
services:
  node-app:
    container_name: hs_website_backend
    image: sunwayne/hswebsitebackend
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - mysql
    networks:
      - hs_website

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - hs_website

volumes:
  mysql-db:

networks:
  hs_website: